title: RAS University
description: A free Robotics University
theme: just-the-docs

url: https://tlucking.github.io/RAS-University/

aux_links:
  Template Repository: https://github.com/TLucking/RAS-University

plugins:
  - jekyll-spaceship

include:
  - assets

nav_order: 1
search_enabled: true

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# Custom CSS
sass:
  load_paths:
    - _sass
    - assets/css

# Add this to ensure Just the Docs includes it
just_the_docs:
  custom_css:
    - /assets/css/custom.css